services:
  browser:
    image: node:16.13-alpine
    user: node
    ports:
      - ${COMPOSE_PORT_BROWSER}:8080
    env_file:
      - ./.env.local
    working_dir: /dist/
    entrypoint: ['npm', 'run', 'start-browser', '--', "--client-web-socket-url-port=${COMPOSE_PORT_BROWSER}", '--port=8080']
    volumes:
      - ./:/dist/

  web:
    image: node:16.13-alpine
    user: node
    ports:
      - ${COMPOSE_PORT_WEB}:8081
    env_file:
      - ./.env.local
    environment:
      EVENT_STORE_PATH: '/tmp/eventstore/'
      REPOSITORY_PATH: '/tmp/repository/'
    working_dir: /dist/
    entrypoint: ['npm', 'run', 'start-web', '8081']
    volumes:
      - ./:/dist/
      - ./var/eventstore/:/tmp/eventstore/
      - ./var/repository/:/tmp/repository/
